global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'smarttalker-core'
    scrape_interval: 5s
    static_configs:
      - targets: ['core:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'gpu'
    static_configs:
      - targets: ['nvidia-gpu-exporter:9445']
